// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SVCW.Models
{
    public partial class ActivityResult
    {
        public ActivityResult()
        {
            Media = new HashSet<Media>();
            Process = new HashSet<Process>();
        }

        [Key]
        [Column("resultId")]
        [StringLength(10)]
        public string ResultId { get; set; }
        [Required]
        [Column("title")]
        public string Title { get; set; }
        [Required]
        [Column("desciption")]
        public string Desciption { get; set; }
        [Column("datetime", TypeName = "datetime")]
        public DateTime Datetime { get; set; }
        [Required]
        [Column("activityId")]
        [StringLength(10)]
        public string ActivityId { get; set; }
        [Column("totalAmount", TypeName = "decimal(18, 0)")]
        public decimal? TotalAmount { get; set; }
        [Column("resultDocument")]
        public string ResultDocument { get; set; }

        [ForeignKey("ActivityId")]
        [InverseProperty("ActivityResult")]
        public virtual Activity Activity { get; set; }
        [InverseProperty("ActivityResult")]
        public virtual ICollection<Media> Media { get; set; }
        [InverseProperty("ActivityResult")]
        public virtual ICollection<Process> Process { get; set; }
    }
}