// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SVCW.Models
{
    public partial class BankAccount
    {
        public BankAccount()
        {
            Activity = new HashSet<Activity>();
        }

        [Key]
        [Column("bankAccountId")]
        [StringLength(10)]
        public string BankAccountId { get; set; }
        [Required]
        [Column("bankAccountName")]
        [StringLength(100)]
        public string BankAccountName { get; set; }
        [Required]
        [Column("bankNumber")]
        [StringLength(20)]
        public string BankNumber { get; set; }
        [Required]
        [Column("bankName")]
        public string BankName { get; set; }
        [Column("description")]
        public string Description { get; set; }
        [Column("status")]
        public bool Status { get; set; }
        [Required]
        [Column("userId")]
        [StringLength(10)]
        public string UserId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("BankAccount")]
        public virtual User User { get; set; }

        [ForeignKey("BankAccountId")]
        [InverseProperty("BankAccount")]
        public virtual ICollection<Activity> Activity { get; set; }
    }
}