// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SVCW.Models
{
    public partial class BanUser
    {
        [Key]
        [Column("banId")]
        [StringLength(10)]
        public string BanId { get; set; }
        [Required]
        [Column("userId")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Required]
        [Column("reasonBan")]
        public string ReasonBan { get; set; }
        [Column("datetime", TypeName = "datetime")]
        public DateTime Datetime { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("BanUser")]
        public virtual User User { get; set; }
    }
}