// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SVCW.Models
{
    public partial class FollowFanpage
    {
        [Key]
        [Column("userId")]
        [StringLength(10)]
        public string UserId { get; set; }
        [Key]
        [Column("fanpageId")]
        [StringLength(10)]
        public string FanpageId { get; set; }
        [Column("datetime", TypeName = "datetime")]
        public DateTime Datetime { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [ForeignKey("FanpageId")]
        [InverseProperty("FollowFanpage")]
        public virtual Fanpage Fanpage { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("FollowFanpage")]
        public virtual User User { get; set; }
    }
}