// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SVCW.Models
{
    public partial class RejectActivity
    {
        [Key]
        [Column("rejectId")]
        [StringLength(10)]
        public string RejectId { get; set; }
        [Required]
        [Column("activityId")]
        [StringLength(10)]
        public string ActivityId { get; set; }
        [Required]
        [Column("reason")]
        public string Reason { get; set; }
        [Column("datetime", TypeName = "datetime")]
        public DateTime Datetime { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [ForeignKey("ActivityId")]
        [InverseProperty("RejectActivity")]
        public virtual Activity Activity { get; set; }
    }
}