// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SVCW.Models
{
    [Index("ReportTypeName", Name = "IX_ReportType", IsUnique = true)]
    public partial class ReportType
    {
        public ReportType()
        {
            Report = new HashSet<Report>();
        }

        [Key]
        [Column("reportTypeId")]
        [StringLength(10)]
        public string ReportTypeId { get; set; }
        [Required]
        [Column("reportTypeName")]
        [StringLength(256)]
        public string ReportTypeName { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [InverseProperty("ReportType")]
        public virtual ICollection<Report> Report { get; set; }
    }
}