// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SVCW.Models
{
    [Index("RoleName", Name = "IX_Role", IsUnique = true)]
    public partial class Role
    {
        public Role()
        {
            User = new HashSet<User>();
        }

        [Key]
        [Column("roleId")]
        [StringLength(10)]
        public string RoleId { get; set; }
        [Required]
        [Column("roleName")]
        [StringLength(100)]
        public string RoleName { get; set; }
        [Required]
        [Column("description")]
        public string Description { get; set; }
        [Column("status")]
        public bool Status { get; set; }

        [InverseProperty("Role")]
        public virtual ICollection<User> User { get; set; }
    }
}